In [11]:
# Python Basics: values, repetition, functions, and lists
student_name = "Bob"
lesson_number = 1
is_ready = True

print(f"Welcome, {student_name}! Lesson {lesson_number} is ready: {is_ready}")

Welcome, Bob! Lesson 1 is ready: True


# Python Basics: A Beginner's Practice Notebook

This notebook introduces:

1. Basic Python data types
2. `while` loops
3. Built-in and user-defined functions
4. Lists and useful methods such as `reverse`, `sort`, and `append`

Run each code cell and change the examples to learn by experimenting.

## 1. Basic Data Types

A **data type** tells Python what kind of value we are storing. The most common beginner types are:

| Type | Example | Use |
|---|---|---|
| `int` | `42` | Whole numbers |
| `float` | `3.14` | Decimal numbers |
| `str` | `"hello"` | Text |
| `bool` | `True` or `False` | Yes/no decisions |
| `None` | `None` | No value yet |

Python can report a value's type with the built-in `type()` function.

In [3]:
# Different basic data types
age = 14                    # int: a whole number
height_m = 1.62             # float: a decimal number
favorite_color = "green"   # str: text
likes_python = True         # bool: True or False
future_score = None         # None: the value is not known yet

values = [age, height_m, favorite_color, likes_python, future_score]
for value in values:
    print(value, "->", type(value).__name__)

# Operators work differently depending on the data type.
print("2 + 3 =", 2 + 3)
print('"Py" + "thon" =', "Py" + "thon")

14 -> int
1.62 -> float
green -> str
True -> bool
None -> NoneType
2 + 3 = 5
"Py" + "thon" = Python


## 2. `while` Loop: Printing Without `end`

### Definition

A `while` loop repeats indented code while its condition is `True`.

### Syntax

```python
while condition:
    statement
    update_value
```

- `while` starts the loop.
- The condition is checked before every repetition.
- The colon `:` begins the loop body.
- Indentation shows which statements belong to the loop.
- The update prevents an infinite loop.

### Understanding `counter += 1`

```python
counter += 1
```

This is shorthand for:

```python
counter = counter + 1
```

It adds `1` to the current value of `counter`. In the list loop, it moves from index `0` to index `1`, then to index `2`, and so on. When the counter becomes `7`, the condition `counter < 7` becomes `False` and the loop stops.

`print(value)` uses a newline by default. Therefore, each number appears on a separate line in the first example.

In [17]:
# Create a list containing 7 numbers.
numbers = [6, 49, 33, 8, 72, 1060, 198]

# Start at index 0, the first position in the list.
counter = 0

print("Original without end=:")
while counter < 7:
    print(numbers[counter])
    counter += 1

Original without end=:
6
49
33
8
72
1060
198


## 3. `print(end=...)`, `sort()`, and `reverse()`

### Definition and syntax of `end`

The `end` argument tells `print()` what to write after the value.

```python
print(value, end=" ")
```

Normally, `print(value)` uses `end="\n"`, which means “move to a new line.” With `end=" "`, the next value stays on the same line and a space is added.

### List method syntax

```python
numbers.sort()       # Arrange from smallest to largest
numbers.reverse()    # Reverse the current order
```

Both methods change the existing list. After changing the list, reset `counter = 0` before looping from the first item again.

In [18]:
# The list already exists from the previous cell.
numbers.sort()

counter = 0  # Reset counter to start at index 0 again.

print("Sorted with end=' ':")
while counter < 7:
    print(numbers[counter], end=" ")
    counter += 1

numbers.reverse()

counter = 0  # Reset counter again for the reversed list.

print("\nReversed with end=' ':")
while counter < 7:
    print(numbers[counter], end=" ")
    counter += 1

print()  # Move to a new line after the loop.

Sorted with end=' ':
6 8 33 49 72 198 1060 
Reversed with end=' ':
1060 198 72 49 33 8 6 


### Dry run: how the three loops work

The list has 7 items, so the condition is `counter < 7`. Each loop starts with `counter = 0`, prints one item, and then increases `counter` by `1`.

| Repetition | `counter` before | Condition | Item printed | `counter` after |
|---:|---:|---|---:|---:|
| 1 | 0 | `0 < 7` is `True` | `numbers[0]` | 1 |
| 2 | 1 | `1 < 7` is `True` | `numbers[1]` | 2 |
| 3 | 2 | `2 < 7` is `True` | `numbers[2]` | 3 |
| 4 | 3 | `3 < 7` is `True` | `numbers[3]` | 4 |
| 5 | 4 | `4 < 7` is `True` | `numbers[4]` | 5 |
| 6 | 5 | `5 < 7` is `True` | `numbers[5]` | 6 |
| 7 | 6 | `6 < 7` is `True` | `numbers[6]` | 7 |
| Stop | 7 | `7 < 7` is `False` | Nothing | Loop ends |

The same process happens three times:

1. **Original:** prints `6 49 33 8 72 1060 198`.
2. **Sorted:** `numbers.sort()` changes the list to `[6, 8, 33, 49, 72, 198, 1060]`. The counter is reset to `0`, then the loop prints the sorted list.
3. **Reversed:** `numbers.reverse()` changes the sorted list to `[1060, 198, 72, 49, 33, 8, 6]`. The counter is reset again, then the loop prints the reversed list.

### Syntax used

```python
numbers.sort()       # Sort the list in ascending order
numbers.reverse()    # Reverse the current list order
counter = 0          # Reset the counter before another pass
```

## 4. Conditional Statements, `break`, and `continue`

### Conditional syntax

```python
if condition:
    # runs when condition is True
elif another_condition:
    # runs when the first condition is False and this is True
else:
    # runs when all previous conditions are False
```

- `if` makes a decision.
- `elif` checks another condition.
- `else` is the fallback choice.
- `break` stops the loop immediately.
- `continue` skips the rest of the current repetition and starts the next repetition.

In [14]:
# if, elif, and else choose one result.
score = 72

if score >= 90:
    grade = "A"
elif score >= 60:
    grade = "Pass"
else:
    grade = "Try again"

print("Grade result:", grade)

# continue skips even numbers; break stops at 9.
for number in range(1, 11):
    if number % 2 == 0:
        continue
    if number == 9:
        break
    print("Odd number before 9:", number)

Grade result: Pass
Odd number before 9: 1
Odd number before 9: 3
Odd number before 9: 5
Odd number before 9: 7


## 3. Functions: Built-in and User-Defined

A **function** is a reusable block of code.

### Built-in function syntax

Built-in functions are already written by Python. We call them using parentheses:

```python
result = function_name(input_value)
```

Examples: `len(text)`, `max(numbers)`, `round(price)`, and `type(value)`.

For simple arithmetic, Python provides these operators:

```python
addition = first_number + second_number
subtraction = first_number - second_number
```

### User-defined function syntax

We create our own function with `def`:

```python
def function_name(parameter1, parameter2):
    result = parameter1 + parameter2
    return result

answer = function_name(value1, value2)
```

- `def` starts the function definition.
- Parameters are the input names inside the parentheses.
- The indented block is the function body.
- `return` sends a result back to the caller.
- The function runs only when we call it.

In [12]:
# Built-in functions are already provided by Python.
# For addition, the + operator is the easiest built-in operation.
first_number = 10
second_number = 5
print("10 + 5 =", first_number + second_number)

# Other useful built-in functions
message = "Learning Python"
prices = [12.5, 8.0, 15.75]
print("Characters:", len(message))
print("Rounded price:", round(prices[0]))
print("Highest price:", max(prices))
print("Type of prices:", type(prices).__name__)

10 + 5 = 15
Characters: 15
Rounded price: 12
Highest price: 15.75
Type of prices: list


In [21]:
# User-defined function: we choose the name, inputs, and result.
def add(first_number, second_number):
    result = first_number + second_number
    return result


def subtract(first_number, second_number):
    result = first_number - second_number
    return result


# Define the functions first, then call them with two arguments.
print("10 + 5 =", add(10, 5))
print("10 - 5 =", subtract(10, 5))

# Another user-defined function

def greet(name):
    return f"Hello, {name}! Welcome to Python."


print(greet("Leo Messi"))

10 + 5 = 15
10 - 5 = 5
Hello, Leo Messi! Welcome to Python.


## 5. Lists and Basic Methods

A **list** stores multiple values in one ordered, changeable collection. List positions start at index `0`.

### List method definitions and syntax

- `append(item)` adds one item to the end.
  ```python
  numbers.append(25)
  ```
- `sort()` arranges items from smallest to largest, or alphabetically.
  ```python
  numbers.sort()
  ```
- `reverse()` reverses the list's current order.
  ```python
  numbers.reverse()
  ```

These methods change the existing list directly. They do not create a separate list. Use `print(numbers)` after each method to see the change.

In [9]:
# Creating, indexing, and changing a list
fruits = ["banana", "apple", "mango"]
print("First fruit:", fruits[0])
print("Last fruit:", fruits[-1])

fruits.append("orange")
print("After append:", fruits)

fruits.sort()
print("After sort:", fruits)

fruits.reverse()
print("After reverse:", fruits)

# Strings are immutable, so use slicing to create a reversed string.
word = "Python"
print("Reversed string:", word[::-1])

First fruit: banana
Last fruit: mango
After append: ['banana', 'apple', 'mango', 'orange']
After sort: ['apple', 'banana', 'mango', 'orange']
After reverse: ['orange', 'mango', 'banana', 'apple']
Reversed string: nohtyP


In [8]:
# A small practice function using a list

def add_score(scores, new_score):
    scores.append(new_score)
    scores.sort()
    return scores

scores = [72, 95, 81]
updated_scores = add_score(scores, 88)
print("Sorted scores:", updated_scores)
print("Number of scores:", len(updated_scores))

Sorted scores: [72, 81, 88, 95]
Number of scores: 4


## 6. Practice Challenge

Create a function named `count_down` that uses a `while` loop to print numbers from a starting number down to `1`, then prints `"Done!"`. Test it with `count_down(5)`.

In [20]:
# Practice challenge solution

def count_down(start_number):
    while start_number >= 1:
        print(start_number)
        start_number -= 1
    print("Done!")


count_down(5)

5
4
3
2
1
Done!
